INSERT INTO `countries` (`name`,`id`)
VALUES
('Sin Datos', 'UNK'),
('Afganistán','AFG'),
('Albania','ALB'),
('Alemania','DEU'),
('Andorra','AND'),
('Angola','AGO'),
('Antigua y Barbuda','ATG'),
('Arabia Saudita','SAU'),
('Argelia','DZA'),
('Argentina','ARG'),
('Armenia','ARM'),
('Australia','AUS'),
('Austria','AUT'),
('Azerbaiyán','AZE'),
('Bahamas','BHS'),
('Bahrein','BHR'),
('Bangladesh','BGD'),
('Barbados','BRB'),
('Belarús','BLR'),
('Belice','BLZ'),
('Benin','BEN'),
('Bhután','BTN'),
('Bolivia','BOL'),
('Bosnia y Herzegovina','BIH'),
('Botswana','BWA'),
('Brasil','BRA'),
('Brunei Darussalam','BRN'),
('Bulgaria','BGR'),
('Burkina Faso','BFA'),
('Burundi','BDI'),
('Bélgica','BEL'),
('Cabo Verde','CPV'),
('Camboya','KHM'),
('Camerún','CMR'),
('Canadá','CAN'),
('Chad','TCD'),
('Chequia','CZE'),
('Chile','CHL'),
('China','CHN'),
('Chipre','CYP'),
('Colombia','COL'),
('Comoras','COM'),
('Congo','COG'),
('Costa Rica','CRI'),
('Croacia','HRV'),
('Cuba','CUB'),
('Côte d''Ivoire','CIV'),
('Dinamarca','DNK'),
('Djibouti','DJI'),
('Dominica','DMA'),
('Ecuador','ECU'),
('Egipto','EGY'),
('El Salvador','SLV'),
('Emiratos Árabes Unidos','ARE'),
('Eritrea','ERI'),
('Eslovaquia','SVK'),
('Eslovenia','SVN'),
('España','ESP'),
('Estados Unidos de América','USA'),
('Estonia','EST'),
('Eswatini','SWZ'),
('Etiopía','ETH'),
('Federación de Rusia','RUS'),
('Fiji','FJI'),
('Filipinas','PHL'),
('Finlandia','FIN'),
('Francia','FRA'),
('Gabón','GAB'),
('Gambia','GMB'),
('Georgia','GEO'),
('Ghana','GHA'),
('Granada','GRD'),
('Grecia','GRC'),
('Guatemala','GTM'),
('Guinea','GIN'),
('Guinea Ecuatorial','GNQ'),
('Guinea-Bissau','GNB'),
('Guyana','GUY'),
('Haití','HTI'),
('Honduras','HND'),
('Hungría','HUN'),
('India','IND'),
('Indonesia','IDN'),
('Iraq','IRQ'),
('Irlanda','IRL'),
('Irán','IRN'),
('Islandia','ISL'),
('Islas Cook','COK'),
('Islas Feroe','FRO'),
('Islas Marshall','MHL'),
('Islas Salomón','SLB'),
('Israel','ISR'),
('Italia','ITA'),
('Jamaica','JAM'),
('Japón','JPN'),
('Jordania','JOR'),
('Kazajstán','KAZ'),
('Kenya','KEN'),
('Kirguistán','KGZ'),
('Kiribati','KIR'),
('Kuwait','KWT'),
('Lesotho','LSO'),
('Letonia','LVA'),
('Liberia','LBR'),
('Libia','LBY'),
('Lituania','LTU'),
('Luxemburgo','LUX'),
('Líbano','LBN'),
('Macedonia del Norte','MKD'),
('Madagascar','MDG'),
('Malasia','MYS'),
('Malawi','MWI'),
('Maldivas','MDV'),
('Malta','MLT'),
('Malí','MLI'),
('Marruecos','MAR'),
('Mauricio','MUS'),
('Mauritania','MRT'),
('Micronesia','FSM'),
('Mongolia','MNG'),
('Montenegro','MNE'),
('Mozambique','MOZ'),
('Myanmar','MMR'),
('México','MEX'),
('Mónaco','MCO'),
('Namibia','NAM'),
('Nauru','NRU'),
('Nepal','NPL'),
('Nicaragua','NIC'),
('Nigeria','NGA'),
('Niue','NIU'),
('Noruega','NOR'),
('Nueva Zelandia','NZL'),
('Níger','NER'),
('Omán','OMN'),
('Pakistán','PAK'),
('Palau','PLW'),
('Panamá','PAN'),
('Papua Nueva Guinea','PNG'),
('Paraguay','PRY'),
('Países Bajos','NLD'),
('Perú','PER'),
('Polonia','POL'),
('Portugal','PRT'),
('Qatar','QAT'),
('Reino Unido de Gran Bretaña e Irlanda del Norte','GBR'),
('República Centroafricana','CAF'),
('República Democrática Popular Lao','LAO'),
('República Democrática del Congo','COD'),
('República Dominicana','DOM'),
('República Popular Democrática de Corea','PRK'),
('República Unida de Tanzanía','TZA'),
('República de Corea','KOR'),
('República de Moldova','MDA'),
('República Árabe Siria','SYR'),
('Rumania','ROU'),
('Rwanda','RWA'),
('Saint Kitts y Nevis','KNA'),
('Samoa','WSM'),
('San Marino','SMR'),
('San Vicente y las Granadinas','VCT'),
('Santa Lucía','LCA'),
('Santo Tomé y Príncipe','STP'),
('Senegal','SEN'),
('Serbia','SRB'),
('Seychelles','SYC'),
('Sierra Leona','SLE'),
('Singapur','SGP'),
('Somalia','SOM'),
('Sri Lanka','LKA'),
('Sudáfrica','ZAF'),
('Sudán','SDN'),
('Sudán del Sur','SSD'),
('Suecia','SWE'),
('Suiza','CHE'),
('Suriname','SUR'),
('Tailandia','THA'),
('Tayikistán','TJK'),
('Timor-Leste','TLS'),
('Togo','TGO'),
('Tokelau','TKL'),
('Tonga','TON'),
('Trinidad y Tabago','TTO'),
('Turkmenistán','TKM'),
('Turquía','TUR'),
('Tuvalu','TUV'),
('Túnez','TUN'),
('Ucrania','UKR'),
('Uganda','UGA'),
('Uruguay','URY'),
('Uzbekistán','UZB'),
('Vanuatu','VUT'),
('Venezuela','VEN'),
('Viet Nam','VNM'),
('Yemen','YEM'),
('Zambia','ZMB'),
('Zimbabwe','ZWE');
